services:
  db: # Definición del servicio de la base de datos PostgreSQL.
    image: postgres:latest # Imagen de Docker utilizada para crear el contenedor, en este caso, la última versión de PostgreSQL.
    restart: always # Configuración para reiniciar el contenedor siempre que Docker o el sistema operativo se reinicien.
    environment:
      - POSTGRES_USER=postgres # Nombre de usuario para la base de datos PostgreSQL.
      - POSTGRES_PASSWORD=postgres # Contraseña del usuario de la base de datos PostgreSQL.
    ports:
      - "5429:5432" 
    volumes:
      - db:/var/lib/postgresql/data # Montaje de un volumen para persistir los datos de la base de datos en el directorio /var/lib/postgresql/data dentro del contenedor.

volumes:
  db: # Definición de un volumen llamado "db".
    driver: local # Tipo de driver de volumen local.

  cache: # Definición de un volumen llamado "cache".
    driver: local # Tipo de driver de volumen local.
